#!/bin/bash
#
# Apply file-type-specific filters to stdin
#
# Arguments:
#   The name of the file being streamed
# Output:
#   Writes filtered stream to stdout

readonly gff_pattern='\.gff(\.|$)'

if [[ "$1" =~ ${gff_pattern} ]]; then
    echo "Sorting GFF file $1" >&2
    if ! grep -v "^#" | sort -t$'\t' -k1,1 -k4,4n; then
	echo "Error filtering contents of GFF file: $1" >&2
    fi
else
    # Default: just forward the stream unmolested
    cat
fi



